version: '3.4'

services:
 tprestaurent.backend.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: tprestaurent.backend.db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "03122002Hq@@"
    volumes:
      - ./.containers/tprestaurent.backend.db:/var/lib/mssql/data
    ports:
      - "1433:1433"

 tprestaurent.backendcore.api:
    image: ${DOCKER_REGISTRY-}tprestaurentbackendcoreapi
    container_name: tprestaurent.backend.api
    build:
      context: .
      dockerfile: TPRestaurent.BackEndCore.API/Dockerfile
    depends_on:
      tprestaurent.backend.db:
        condition: service_started
    ports:
    - "3000:80"
    - "3001:443"